<h1>Customer Notes</h1>
<?php 

$customer_notes = $block->getNotes();
$customer_notes_collection = $block->getNotesCollection();
$customer_notes_page_size = $block->getPageSize();
$customers = $block->getCustomers();
$showTagsOnList = $block->getShowTagsOnList();
$showPaginationOnList = $block->getShowPaginationOnList();
$showAddNoteFormOnList = $block->getShowAddNoteFormOnList();
$tags = $block->getTags();

if( is_array( $customer_notes ) && count( $customer_notes ) > 0 ) {
    foreach( $customer_notes as $customer_note ) {
        $noteTagsHtml = $showTagsOnList ? $customer_note->getNoteTagsHtml() : '';
        $customer = $customer_note->getNoteCustomer($customer_note->getCustomerId());
        ?>
        <div>
            <p>
                <?php 
                    if( is_array($customer) && count($customer) > 0 ) {
                        echo '<strong>' . $customer['firstname'] . ' ' . $customer['lastname'] . '</strong> ( <em>' . $customer['email'] . '</em> )  @ ';
                    }
                    
                    echo date('F j, Y', strtotime($customer_note->getCreatedAt())) . ': ';
                
                    echo '<strong>"' . $customer_note->getNote() . '"</strong>';
                ?>
                <a href="<?php echo $block->getUrl('notes/index/edit', ['note_id' => $customer_note->getId()]); ?>" class="edit-note" data-url="<?php echo $block->getUrl('notes/index/edit', ['note_id' => $customer_note->getId()]); ?>">Edit</a>
                or
                <a href="<?php echo $block->getUrl('notes/index/trash', ['note_id' => $customer_note->getId()]); ?>" class="trash-note" data-url="<?php echo $block->getUrl('notes/index/trash', ['note_id' => $customer_note->getId()]); ?>">Move to Trash</a>
                ;
                <a href="<?php echo $block->getUrl('notes/index/history', ['note_id' => $customer_note->getId()]); ?>" class="note-history" data-url="<?php echo $block->getUrl('notes/index/history', ['note_id' => $customer_note->getId()]); ?>">Show History</a>
                <?php echo $noteTagsHtml; ?>
            </p>
        </div>
    <?php }
} ?>

<p><a href="<?php echo $block->getUrl('notes/index/trashed'); ?>">View trashed notes</a></p>

<?php if ($showPaginationOnList) {
    $pagerBlock = $block->getLayout()->createBlock(\Magento\Theme\Block\Html\Pager::class, 'customer_notes_pager');
    $pagerBlock->setAvailableLimit([$customer_notes_page_size => $customer_notes_page_size]);
    $pagerBlock->setShowPerPage(true);
    $pagerBlock->setCollection($customer_notes_collection);
    echo $pagerBlock->toHtml();
} ?>

<?php if ($showAddNoteFormOnList) { ?>
    <h2>Add Customer Note:</h2>
    <form id="add-note-form" action="<?php echo $block->getUrl('notes/index/add'); ?>" method="post">
        <label for="note">Note:</label>
        <textarea id="note" name="note" required></textarea>
        <br/>
        <?php if(is_array($customers) && count($customers) > 0) { ?>
            <label for="customer">Customer:</label>
            <select id="customer" name="customer" required>
                <option>Choose Customer</option>
                <?php foreach($customers as $customer) { ?>
                    <option value="<?php echo $customer['entity_id']; ?>"><?php echo $customer['firstname'] . ' ' . $customer['lastname']; ?></option>
                <?php } ?>
            </select>
        <?php } ?>
        <br/>
        <?php if(is_array($tags) && count($tags) > 0) { ?>
            <label for="tags">Tags:</label>
            <select id="tags" name="tags[]" required multiple>
                <?php foreach($tags as $tag) { ?>
                    <option value="<?php echo $tag->getTagId(); ?>"><?php echo $tag->getName(); ?></option>
                <?php } ?>
            </select>
        <?php } ?>
        <br/>
        <br/>
        <button class="action primary" type="submit">Add Note</button>
    </form>
<?php } ?>