<h1>Customer Notes</h1>
<?php 

$customerNotes = $block->getNotes();
$customerNotesCollection = $block->getNotesCollection();
$customerNotesPageSize = $block->getListPageSize();
$customers = $block->getCustomers();
$isListTagsFilterEnabled = $block->isListTagsFilterEnabled();
$isListTagsEnabled = $block->isListTagsEnabled();
$isListPaginationEnabled = $block->isListPaginationEnabled();
$isListAddNoteFormEnabled = $block->isListAddNoteFormEnabled();
$tags = $block->getTags(); 
$currentTagId = $this->getRequest()->getParam('tag_id');

?>

<?php if ($isListTagsFilterEnabled && is_array($tags) && count($tags) > 0) { ?>
    <div class="notes-list-filter-holder tag-filters">
        <div class="filter-intro">
            <span class="">Filter by tags:</span>
        </div>
        <div class="filter-item <?php echo !$currentTagId ? 'active' : ''; ?>">
            <a href="<?php echo $block->getUrl('notes'); ?>">
                All
            </a>
        </div>
        <?php foreach ($tags as $tag) { 
            $isActive = ($currentTagId == $tag->getTagId()) ? 'active' : '';
        ?>
            <div class="filter-item <?php echo $isActive; ?>">
                <a href="<?php echo $block->getUrl('notes', ['tag_id' => $tag->getTagId()]); ?>">
                    <?php echo $tag->getName(); ?>
                </a>
            </div>
        <?php } ?>
    </div>
<?php } ?>

<div class="notes-holder">
    <?php if( is_array( $customerNotes ) && count( $customerNotes ) > 0 ) { ?>
        <?php foreach( $customerNotes as $customerNote ) {
            $noteTagsHtml = $isListTagsEnabled ? $customerNote->getNoteTagsHtml() : '';
            $customer = $customerNote->getNoteCustomer($customerNote->getCustomerId());
            ?>
            <div>
                <p>
                    <?php 
                        if( is_array($customer) && count($customer) > 0 ) {
                            echo '<strong>' . $customer['firstname'] . ' ' . $customer['lastname'] . '</strong> ( <em>' . $customer['email'] . '</em> )  @ ';
                        }
                        
                        echo date('F j, Y', strtotime($customerNote->getCreatedAt())) . ': ';
                    
                        echo '<strong>"' . $customerNote->getNote() . '"</strong>';
                    ?>
                    <a href="<?php echo $block->getUrl('notes/index/edit', ['note_id' => $customerNote->getId()]); ?>" class="edit-note" data-url="<?php echo $block->getUrl('notes/index/edit', ['note_id' => $customerNote->getId()]); ?>">Edit</a>
                    or
                    <a href="<?php echo $block->getUrl('notes/index/trash', ['note_id' => $customerNote->getId()]); ?>" class="trash-note" data-url="<?php echo $block->getUrl('notes/index/trash', ['note_id' => $customerNote->getId()]); ?>">Move to Trash</a>
                    ;
                    <a href="<?php echo $block->getUrl('notes/index/history', ['note_id' => $customerNote->getId()]); ?>" class="note-history" data-url="<?php echo $block->getUrl('notes/index/history', ['note_id' => $customerNote->getId()]); ?>">Show History</a>
                    <?php echo $noteTagsHtml; ?>
                </p>
            </div>
        <?php } ?>
    <?php } else { ?>
        <p>No notes found matching provided criteria.</p>
    <?php } ?>
</div>

<?php if ($isListPaginationEnabled) {
    $pagerBlock = $block->getLayout()->createBlock(\Magento\Theme\Block\Html\Pager::class, 'customer_notes_pager');
    $pagerBlock->setAvailableLimit([$customerNotesPageSize => $customerNotesPageSize]);
    $pagerBlock->setShowPerPage(true);
    $pagerBlock->setCollection($customerNotesCollection);
    echo $pagerBlock->toHtml();
} ?>

<p><a href="<?php echo $block->getUrl('notes/index/trashed'); ?>">View trashed notes</a></p>

<?php if ($isListAddNoteFormEnabled) { ?>
    <h4><a href="#" class="add-note-form-trigger">Add Customer Note</a></h2>
    <form id="add-note-form" action="<?php echo $block->getUrl('notes/index/add'); ?>" method="post" style="display: none;">
        <label for="note">Note:</label>
        <textarea id="note" name="note" required></textarea>
        <br/>
        <?php if(is_array($customers) && count($customers) > 0) { ?>
            <label for="customer">Customer:</label>
            <select id="customer" name="customer" required>
                <option>Choose Customer</option>
                <?php foreach($customers as $customer) { ?>
                    <option value="<?php echo $customer['entity_id']; ?>"><?php echo $customer['firstname'] . ' ' . $customer['lastname']; ?></option>
                <?php } ?>
            </select>
        <?php } ?>
        <br/>
        <?php if(is_array($tags) && count($tags) > 0) { ?>
            <label for="tags">Tags:</label>
            <select id="tags" name="tags[]" multiple>
                <?php foreach($tags as $tag) { ?>
                    <option value="<?php echo $tag->getTagId(); ?>"><?php echo $tag->getName(); ?></option>
                <?php } ?>
            </select>
        <?php } ?>
        <br/>
        <br/>
        <button class="action primary" type="submit">Add Note</button>
    </form>
<?php } ?>