<?php
$noteId = $block->getNoteId();
$noteHistoryItems = $block->getNoteHistoryItems();
$customerNotesCollection = $block->getNoteHistoryCollection();
$customerNotesPageSize = $block->getHistoryListPageSize();
$isHistoryListPaginationEnabled = $block->isHistoryListPaginationEnabled();
?>

<h1>History of Note ID: <?= $noteId ?></h1>

<div class="notes-holder note-history">
    <?php if(is_array($noteHistoryItems) && count($noteHistoryItems) ) {
        foreach($noteHistoryItems as $noteHistoryItem) { ?>
            <div>
                <?php echo $noteHistoryItem->getModifiedAt(); ?> - <?php echo $noteHistoryItem->getPreviousNote(); ?>
                <a href="<?php echo $block->getUrl('notes/index/revert', ['note_id' => $noteId, 'history_id' => $noteHistoryItem->getHistoryId()]); ?>" class="revert-note" data-url="<?php echo $block->getUrl('notes/index/revert', ['note_id' => $noteId, 'history_id' => $noteHistoryItem->getHistoryId()]); ?>">revert</a>
                or
                <a href="<?php echo $block->getUrl('notes/index/deletehistory', ['history_id' => $noteHistoryItem->getHistoryId()]); ?>" class="delete-history" data-url="<?php echo $block->getUrl('notes/index/deletehistory', ['history_id' => $noteHistoryItem->getHistoryId()]); ?>">delete</a>
            </div>
        <?php }
    } else { ?>
        <p>No history found for this note!</p>
    <?php } ?>
</div>

<?php if ($isHistoryListPaginationEnabled) {
    $pagerBlock = $block->getLayout()->createBlock(\Magento\Theme\Block\Html\Pager::class, 'customer_notes_pager');
    $pagerBlock->setAvailableLimit([$customerNotesPageSize => $customerNotesPageSize]);
    $pagerBlock->setShowPerPage(true);
    $pagerBlock->setCollection($customerNotesCollection);
    echo $pagerBlock->toHtml();
} ?>

<p class="back-to-notes"><a href="<?php echo $block->getUrl('notes'); ?>">Back to Notes</a></p>