<h1>Trashed Customer Notes</h1>
<?php 

$trashed_notes = $block->getItems();

if( is_array( $trashed_notes ) && count( $trashed_notes ) > 0 ) {
    foreach( $trashed_notes as $trashed_note ) { 
        $customer = $trashed_note->getNoteCustomer($trashed_note->getCustomerId());
        ?>
        <div>
            <p>
                <?php 
                    if( is_array($customer) && count($customer) > 0 ) {
                        echo '<strong>' . $customer['firstname'] . ' ' . $customer['lastname'] . '</strong> ( <em>' . $customer['email'] . '</em> )  @ ';
                    }
                    
                    echo date('F j, Y', strtotime($trashed_note->getCreatedAt())) . ': ';
                
                    echo '<strong>"' . $trashed_note->getNote() . '"</strong>';
                ?>
                <a href="<?php echo $block->getUrl('notes/index/restore', ['note_id' => $trashed_note->getId()]); ?>" class="restore-note" data-url="<?php echo $block->getUrl('notes/index/restore', ['note_id' => $trashed_note->getId()]); ?>">
                    Restore
                </a>
                or
                <a href="<?php echo $block->getUrl('notes/index/delete', ['note_id' => $trashed_note->getId()]); ?>" class="delete-note" data-url="<?php echo $block->getUrl('notes/index/delete', ['note_id' => $trashed_note->getId()]); ?>">
                    Delete Permanently
                </a>
            </p>
        </div>
    <?php }
} ?>

<p><a href="<?php echo $block->getUrl('notes'); ?>">Back to Notes</a></p>