<h1>Trashed Customer Notes</h1>
<?php 
$trashedNotes = $block->getItems(); 
$customerNotesCollection = $block->getItemsCollection();
$customerNotesPageSize = $block->getTrashListPageSize();
$isTrashListPaginationEnabled = $block->isTrashListPaginationEnabled();
?>

<div class="notes-holder trashed-notes">
    <?php if( is_array( $trashedNotes ) && count( $trashedNotes ) > 0 ) { ?>
        <?php foreach( $trashedNotes as $trashedNote ) { 
            $customer = $trashedNote->getNoteCustomer($trashedNote->getCustomerId()); ?>
            <div>
                <p>
                    <?php 
                        if( is_array($customer) && count($customer) > 0 ) {
                            echo '<strong>' . $customer['firstname'] . ' ' . $customer['lastname'] . '</strong> ( <em>' . $customer['email'] . '</em> )  @ ';
                        }
                        
                        echo date('F j, Y', strtotime($trashedNote->getCreatedAt())) . ': ';
                    
                        echo '<strong>"' . $trashedNote->getNote() . '"</strong>';
                    ?>
                    <a href="<?php echo $block->getUrl('notes/index/restore', ['note_id' => $trashedNote->getId()]); ?>" class="restore-note" data-url="<?php echo $block->getUrl('notes/index/restore', ['note_id' => $trashedNote->getId()]); ?>">
                        Restore
                    </a>
                    or
                    <a href="<?php echo $block->getUrl('notes/index/delete', ['note_id' => $trashedNote->getId()]); ?>" class="delete-note" data-url="<?php echo $block->getUrl('notes/index/delete', ['note_id' => $trashedNote->getId()]); ?>">
                        Delete Permanently
                    </a>
                </p>
            </div>
        <?php 
        }
    } else { ?>
    <p>No trashed notes at the moment!</p>
<?php } ?>
</div>

<?php if ($isTrashListPaginationEnabled) {
    $pagerBlock = $block->getLayout()->createBlock(\Magento\Theme\Block\Html\Pager::class, 'customer_notes_pager');
    $pagerBlock->setAvailableLimit([$customerNotesPageSize => $customerNotesPageSize]);
    $pagerBlock->setShowPerPage(true);
    $pagerBlock->setCollection($customerNotesCollection);
    echo $pagerBlock->toHtml();
} ?>

<p class="back-to-notes"><a href="<?php echo $block->getUrl('notes'); ?>">Back to Notes</a></p>