<?php
$tagName = $block->getTagName();
$customerNotes = $block->getTagNotes();
$customerNotesCollection = $block->getTagNotesCollection();
$customerNotesPageSize = $block->getTagSinglePageSize();
$customers = $block->getCustomers();
$isTagSinglePaginationEnabled = $block->isTagSinglePaginationEnabled();

if ($tagName) { ?>
    <h1>Notes tagged as "<?= $tagName ?>"</h1>

    <?php if( is_array( $customerNotes ) && count( $customerNotes ) > 0 ) { ?>
        <div class="notes-holder tagged-notes">
            <?php foreach( $customerNotes as $customerNote ) {
                $noteTagsHtml = $customerNote->getNoteTagsHtml();
                $customer = $customerNote->getNoteCustomer($customerNote->getCustomerId());
                ?>
                <div>
                    <p>
                        <?php 
                            if( is_array($customer) && count($customer) > 0 ) {
                                echo '<strong>' . $customer['firstname'] . ' ' . $customer['lastname'] . '</strong> ( <em>' . $customer['email'] . '</em> )  @ ';
                            }
                            
                            echo date('F j, Y', strtotime($customerNote->getCreatedAt())) . ': ';
                        
                            echo '<strong>"' . $customerNote->getNote() . '"</strong>';
                        ?>
                        <a href="<?php echo $block->getUrl('notes/index/edit', ['note_id' => $customerNote->getId()]); ?>" class="edit-note" data-url="<?php echo $block->getUrl('notes/index/edit', ['note_id' => $customerNote->getId()]); ?>">Edit</a>
                        or
                        <a href="<?php echo $block->getUrl('notes/index/trash', ['note_id' => $customerNote->getId()]); ?>" class="trash-note" data-url="<?php echo $block->getUrl('notes/index/trash', ['note_id' => $customerNote->getId()]); ?>">Move to Trash</a>
                        ;
                        <a href="<?php echo $block->getUrl('notes/index/history', ['note_id' => $customerNote->getId()]); ?>" class="note-history" data-url="<?php echo $block->getUrl('notes/index/history', ['note_id' => $customerNote->getId()]); ?>">Show History</a>
                    </p>
                </div>
            <?php } ?>
        </div>
        
        <?php if ($isTagSinglePaginationEnabled) {
            $pagerBlock = $block->getLayout()->createBlock(\Magento\Theme\Block\Html\Pager::class, 'customer_notes_pager');
            $pagerBlock->setAvailableLimit([$customerNotesPageSize => $customerNotesPageSize]);
            $pagerBlock->setShowPerPage(true);
            $pagerBlock->setCollection($customerNotesCollection);
            echo $pagerBlock->toHtml();
        }

    } else { ?>
    <div class="notes-holder tagged-notes">
        <p>No notes found for this tag!</p>
    </div>
    <?php }
} else { ?>
    <div class="notes-holder tagged-notes">
        <p>The tag you have selected does not exist!</p>
    </div>
<?php } ?>
<p class="back-to-notes"><a href="<?php echo $block->getUrl('notes'); ?>">Back to Notes</a></p>