<?php
    $post = $block->getPost();
?>

<div class="post-single-outer-holder">
    <?php if ($post) { 
        $recentPosts = $post->getRecentPosts();
        $relatedPosts = $post->getRelatedPosts();
        $popularPosts = $post->getPopularPosts();
    ?>
        
        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                ->setTemplate('Krga_Blog::parts/featured-image.phtml')
                ->setData([
                    'parent_block' => $block,
                    'post' => $post,
                    'type' => 'single'
                ])
                ->toHtml();
        ?>

        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                ->setTemplate('Krga_Blog::parts/title.phtml')
                ->setData([
                    'parent_block' => $block,
                    'post' => $post,
                    'type' => 'single'
                ])
                ->toHtml();
        ?>

        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                ->setTemplate('Krga_Blog::parts/tags.phtml')
                ->setData([
                    'parent_block' => $block,
                    'post' => $post,
                    'type' => 'single'
                ])
                ->toHtml(); 
        ?>

        <div class="post-content">
            <?php echo $post->getPostContent(); ?>
        </div>

        <div class="post-info">
            <?php 
                echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setTemplate('Krga_Blog::parts/author.phtml')
                    ->setData([
                        'parent_block' => $block,
                        'post' => $post
                    ])
                    ->toHtml();

                echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setTemplate('Krga_Blog::parts/date.phtml')
                    ->setData([
                        'parent_block' => $block,
                        'post' => $post
                    ])
                    ->toHtml();

                echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setTemplate('Krga_Blog::parts/reading-time.phtml')
                    ->setData([
                        'parent_block' => $block,
                        'post' => $post
                    ])
                    ->toHtml();
                
                echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setTemplate('Krga_Blog::parts/views.phtml')
                    ->setData([
                        'parent_block' => $block,
                        'post' => $post
                    ])
                    ->toHtml();
            ?>
        </div>
        
        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
            ->setTemplate('Krga_Blog::parts/comments.phtml')
            ->setData([
                'parent_block' => $block,
                'post' => $post
            ])
            ->toHtml(); 
        ?>

        <?php if (count($recentPosts)) : ?>
            <div class="recent-posts-outer">
                <h3 class="recent-posts-intro-title">Recent Posts</h3>
                <div class="posts-holder recent-posts">
                    <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Krga_Blog::post-single/parts/post-list.phtml')
                            ->setData([
                                'parent_block' => $block,
                                'posts' => $recentPosts
                            ])
                            ->toHtml(); 
                    ?>
                </div>
            </div>
        <?php endif; ?>

        <?php if (count($relatedPosts)) : ?>
            <div class="related-posts-outer">
                <h3 class="related-posts-intro-title">Related Posts</h3>
                <div class="posts-holder related-posts">
                    <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Krga_Blog::post-single/parts/post-list.phtml')
                            ->setData([
                                'parent_block' => $block,
                                'posts' => $relatedPosts
                            ])
                            ->toHtml(); 
                    ?>
                </div>
            </div>
        <?php endif; ?>

        <?php if (count($popularPosts)) : ?>
            <div class="popular-posts-outer">
                <h3 class="popular-posts-intro-title">Popular Posts</h3>
                <div class="posts-holder popular-posts">
                    <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Krga_Blog::post-single/parts/post-list.phtml')
                            ->setData([
                                'parent_block' => $block,
                                'posts' => $popularPosts
                            ])
                            ->toHtml(); 
                    ?>
                </div>
            </div>
        <?php endif; ?>

    <?php } else { ?>
        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
            ->setTemplate('Krga_Blog::parts/no-results.phtml')
            ->toHtml();
        ?>
    <?php } ?>
</div>