<?php

$parentBlock = $block->getData('parent_block');
$posts = $block->getData('posts');

if (!empty($posts) && is_array($posts)) : ?>
    <?php foreach ($posts as $post) : 
        $postTagsHtml = $post->getPostTagsHtml();
        $author = $post->getPostAuthorFullInfo($post->getPostAuthor());
        $commentsCountInfo = $post->getPostCommentCountInfo();
        $featuredImage = $parentBlock->getImageUrl($post->getPostImage());
    ?>
        <div class="post-holder">
            <div class="post-holder-inner">
                
                <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setTemplate('Krga_Blog::parts/featured-image.phtml')
                    ->setData([
                        'parent_block' => $parentBlock,
                        'post' => $post,
                        'type' => 'single'
                    ])
                    ->toHtml();
                ?>

                <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setTemplate('Krga_Blog::parts/title.phtml')
                    ->setData([
                        'parent_block' => $parentBlock,
                        'post' => $post,
                        'type' => 'list'
                    ])
                    ->toHtml();
                ?>

                <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setTemplate('Krga_Blog::parts/tags.phtml')
                    ->setData([
                        'parent_block' => $parentBlock,
                        'post' => $post,
                        'type' => 'single'
                    ])
                    ->toHtml(); 
                ?>

                <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setTemplate('Krga_Blog::parts/excerpt.phtml')
                    ->setData([
                        'parent_block' => $parentBlock,
                        'post' => $post,
                    ])
                    ->toHtml(); 
                ?>

                <div class="post-info">
                    <?php 
                        echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Krga_Blog::parts/author.phtml')
                            ->setData([
                                'parent_block' => $block,
                                'post' => $post
                            ])
                            ->toHtml();
                        
                        echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Krga_Blog::parts/date.phtml')
                            ->setData([
                                'parent_block' => $block,
                                'post' => $post
                            ])
                            ->toHtml();
                            
                        echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Krga_Blog::parts/comments-count.phtml')
                            ->setData([
                                'parent_block' => $block,
                                'post' => $post
                            ])
                            ->toHtml();
                    ?>
                </div>
            </div>
            
            <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                    ->setTemplate('Krga_Blog::parts/link-overlay.phtml')
                    ->setData([
                        'parent_block' => $parentBlock,
                        'post' => $post
                    ])
                    ->toHtml();
            ?>

        </div>
    <?php endforeach; ?>
<?php endif; ?>
