<?php 

$parentBlock = $block->getData('parent_block');
$post = $block->getData('post');
$type = $block->getData('type');

$titleTag = $type === 'single' ? 'h1' : 'h3';

?>

<<?php echo $titleTag; ?> class="post-title">
    <?php if( $type !== 'single' ) { ?>
        <a class="post-link" href="<?php echo $block->getUrl('posts/post/index', ['post_id' => $post->getPostId()]); ?>">
    <?php } ?>
            <?php echo $post->getPostTitle(); ?>
    <?php if( $type !== 'single' ) { ?>
        </a>
    <?php } ?>
</<?php echo $titleTag; ?>>