<?php $allTags = $block->getAllTags(); ?>

<h1>Tags</h1>
<div class="tags-holder">
    <?php if( is_array( $allTags ) && count( $allTags ) > 0 ) { ?>
        <?php foreach( $allTags as $tag ) {
            ?>
            <div>
                <p>
                    <a href="<?php echo $block->getUrl('posts/tags/index', ['tag_id' => $tag->getTagId()]); ?>">
                        <?php echo $tag->getTagName(); ?>
                        <span>(<?php echo $tag->getTagPostsCount(); ?>)</span>
                    </a>
                </p>
            </div>
        <?php }
    } else { ?>
        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
            ->setTemplate('Krga_Blog::parts/no-results.phtml')
            ->toHtml();
        ?>
<?php } ?>
</div>

<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
    ->setTemplate('Krga_Blog::parts/pagination.phtml')
    ->setData([
        'parent_block' => $block,
        'type' => 'tags_list'
    ])
    ->toHtml(); 
?>