<?php $posts = $block->getPosts(); ?>

<div class="posts-list-outer-holder">
    <h1>Posts</h1>
    
    <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
            ->setTemplate('Krga_Blog::parts/tags-filter.phtml')
            ->setData([
                'parent_block' => $block
            ])
            ->toHtml();
    ?>

    <div class="posts-holder">
        <?php if( is_array( $posts ) && count( $posts ) > 0 ) { ?>
            <?php foreach( $posts as $post ) { ?>
                <div class="post-holder">
                    <div class="post-holder-inner">
                        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                                ->setTemplate('Krga_Blog::parts/featured-image.phtml')
                                ->setData([
                                    'parent_block' => $block,
                                    'post' => $post,
                                    'type' => 'list'
                                ])
                                ->toHtml();
                        ?>
                        
                        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                                ->setTemplate('Krga_Blog::parts/title.phtml')
                                ->setData([
                                    'parent_block' => $block,
                                    'post' => $post,
                                    'type' => 'list'
                                ])
                                ->toHtml();
                        ?>

                        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Krga_Blog::parts/tags.phtml')
                            ->setData([
                                'parent_block' => $block,
                                'post' => $post,
                                'type' => 'list'
                            ])
                            ->toHtml(); 
                        ?>
                        
                        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Krga_Blog::parts/excerpt.phtml')
                            ->setData([
                                'parent_block' => $block,
                                'post' => $post,
                            ])
                            ->toHtml(); 
                        ?>
                        
                        <div class="post-info">
                            <?php 
                                echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                                    ->setTemplate('Krga_Blog::parts/author.phtml')
                                    ->setData([
                                        'parent_block' => $block,
                                        'post' => $post
                                    ])
                                    ->toHtml();
                                
                                echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                                    ->setTemplate('Krga_Blog::parts/date.phtml')
                                    ->setData([
                                        'parent_block' => $block,
                                        'post' => $post
                                    ])
                                    ->toHtml();
                                    
                                echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                                    ->setTemplate('Krga_Blog::parts/comments-count.phtml')
                                    ->setData([
                                        'parent_block' => $block,
                                        'post' => $post
                                    ])
                                    ->toHtml();
                            ?>
                        </div>
                    </div>
                    <a class="post-link post-link-overlay" href="<?php echo $block->getUrl('posts/post/index', ['post_id' => $post->getPostId()]); ?>"></a>
                </div>
            <?php } ?>
        <?php } else { ?>
            <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                ->setTemplate('Krga_Blog::parts/no-results.phtml')
                ->toHtml();
            ?>
        <?php } ?>
    </div>

    <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate('Krga_Blog::parts/pagination.phtml')
        ->setData([
            'parent_block' => $block,
            'type' => 'list'
        ])
        ->toHtml(); 
    ?>
</div>