<?php 

$posts = $block->getPostData();
$post_categories = $block->getPostCategories();

if( $posts && count($posts) > 0 ) {
    foreach( $posts as $post ) { ?>
        <h1><?php echo $post->getPostTitle(); ?></h1>
        <?php if( $post_categories && count($post_categories) > 0 ) { ?>
            <h5>
                <?php foreach( $post_categories as $post_category ) {?>
                    <span><?php echo $post_category['name']; ?></span>
                <?php } ?>
            </h5>
        <?php } ?>
        <p><?php echo $post->getPostContent(); ?></p>
        <h6><?php echo date('F j, Y', strtotime($post->getCreatedAt())); ?></h6>
<?php }
}

