<div class="posts-list-outer-holder">
    
    <?php 

    $tagName = $block->getTagName();
    $posts = $block->getTagPosts();
    $postsCollection = $block->getTagPostsCollection();
    $postsPageSize = $block->getTagSinglePageSize();
    $isListPaginationEnabled = $block->isTagSinglePaginationEnabled();

    ?>

    <h1>Posts tagged as: <?php echo $tagName; ?></h1>
    <div class="posts-holder">
        <?php if( is_array( $posts ) && count( $posts ) > 0 ) { ?>
            <?php foreach( $posts as $post ) {
                $author = $post->getPostAuthorFullInfo($post->getPostAuthor());
                $commentsCountInfo = $post->getPostCommentCountInfo();
                ?>
                <div class="post-holder">
                    <div class="post-holder-inner">
                        <?php 
                            $featuredImage = $block->getImageUrl($post->getPostImage());

                            if (!empty($featuredImage)) { ?>
                                <div class="post-image">
                                    <img src="<?= $featuredImage; ?>" alt="Post Image" />
                                </div>
                            <?php }
                        
                        ?>
                        <h3 class="post-title">
                            <a class="post-link" href="<?php echo $block->getUrl('posts/post/index', ['post_id' => $post->getPostId()]); ?>">
                                <?php echo $post->getPostTitle(); ?>
                            </a>
                        </h3>

                        <h6 class="post-tags">
                            <?php echo $post->getPostTagsHtml(); ?>
                        </h6>

                        <p class="post-excerpt"><?php echo $post->getPostExcerpt(); ?></p>
                        
                        <div class="post-info">
                            <?php 
                                if( is_array($author) && count($author) > 0 ) {
                                    echo '<span class="author">Written by ' . $author['firstname'] . ' ' . $author['lastname'] . '</span>';
                                }
                                
                                echo '<span class="date"> at ' . date('F j, Y', strtotime($post->getCreatedAt())) . '</span>';
                            ?>
                            <?php echo $commentsCountInfo; ?>
                        </div>
                    </div>
                    <a class="post-link post-link-overlay" href="<?php echo $block->getUrl('posts/post/index', ['post_id' => $post->getPostId()]); ?>"></a>
                </div>
            <?php } ?>
        <?php } else { ?>
            <p>No posts found matching provided criteria.</p>
        <?php } ?>
    </div>

    <?php if ($isListPaginationEnabled) {
        $pagerBlock = $block->getLayout()->createBlock(\Magento\Theme\Block\Html\Pager::class, 'tagged_posts_pager');
        $pagerBlock->setAvailableLimit([$postsPageSize => $postsPageSize]);
        $pagerBlock->setShowPerPage(true);
        $pagerBlock->setCollection($postsCollection);
        echo $pagerBlock->toHtml();
    } ?>
</div>