<?php

$tagName = $block->getTagName();
$posts = $block->getTagPosts();

?>

<div class="posts-list-outer-holder">
    <h1>Posts tagged as: <?php echo $tagName; ?></h1>
    <div class="posts-holder">
        <?php if( is_array( $posts ) && count( $posts ) > 0 ) { ?>
            <?php foreach( $posts as $post ) {
                $author = $post->getPostAuthorFullInfo($post->getPostAuthor());
                $commentsCountInfo = $post->getPostCommentCountInfo();
                ?>
                <div class="post-holder">
                    <div class="post-holder-inner">
                        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                                ->setTemplate('Krga_Blog::parts/featured-image.phtml')
                                ->setData([
                                    'parent_block' => $block,
                                    'post' => $post,
                                    'type' => 'tag_single'
                                ])
                                ->toHtml();
                        ?>
                        
                        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                                ->setTemplate('Krga_Blog::parts/title.phtml')
                                ->setData([
                                    'parent_block' => $block,
                                    'post' => $post,
                                    'type' => 'tag_single'
                                ])
                                ->toHtml();
                        ?>

                        <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                            ->setTemplate('Krga_Blog::parts/tags.phtml')
                            ->setData([
                                'parent_block' => $block,
                                'post' => $post,
                                'type' => 'tag_single'
                            ])
                            ->toHtml(); 
                        ?>

                        <p class="post-excerpt"><?php echo $post->getPostExcerpt(); ?></p>
                        
                        <div class="post-info">
                            <?php 
                                echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                                    ->setTemplate('Krga_Blog::parts/author.phtml')
                                    ->setData([
                                        'parent_block' => $block,
                                        'post' => $post
                                    ])
                                    ->toHtml();
                                
                                echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                                    ->setTemplate('Krga_Blog::parts/date.phtml')
                                    ->setData([
                                        'parent_block' => $block,
                                        'post' => $post
                                    ])
                                    ->toHtml();
                                    
                                echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
                                    ->setTemplate('Krga_Blog::parts/comments-count.phtml')
                                    ->setData([
                                        'parent_block' => $block,
                                        'post' => $post
                                    ])
                                    ->toHtml();
                            ?>
                        </div>
                    </div>
                    <a class="post-link post-link-overlay" href="<?php echo $block->getUrl('posts/post/index', ['post_id' => $post->getPostId()]); ?>"></a>
                </div>
            <?php } ?>
        <?php } else { ?>
            <p>No posts found matching provided criteria.</p>
        <?php } ?>
    </div>

    <?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')
        ->setTemplate('Krga_Blog::parts/pagination.phtml')
        ->setData([
            'parent_block' => $block,
            'type' => 'tag_single'
        ])
        ->toHtml(); 
    ?>
</div>